version: '2'

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    volumes:
      - .:/config
      - ./transcode:/transcode
      - ../../media:/data
    env_file: ../id.env
    
networks:
  default:
    external:
      name: media