version: '2'

services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    ports:
      - 9117:9117
    volumes:
      - ../:/config
      - ../../downloads/watch:/downloads
      - /etc/localtime:/etc/localtime:ro
    env_file: ../id.env
    
networks:
  default:
    external:
      name: media