version: '2'

services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    restart: always
    network_mode: host
    volumes:
      - .:/config
      - ../../downloads:/downloads
    env_file: ../id.env

networks:
  default:
    external:
      name: media