version: '2'

services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    restart: always
    ports:
      - 6789:6789
    volumes:
      - .:/config
      - ../../downloads:/downloads
    env_file: ../id.env

networks:
  default:
    external:
      name: media